name: Build Android

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
            distribution: 'zulu'
            java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install app dependencies
        run: npm install

      - name: Capacitor init
        run: npm run capInit

      - name: Capacitor add android
        run: npm run android

      - name: Capacitor sync
        run: npm run sync

      - name: versionApp
        run: npm run versionApp
      
      - name: Trapeze
        run: npm run trapeze

      - name: Build app bundle
        run: cd android && gradle bundle

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign dev build
        run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60
